# Machine Learning 1 - Nearest Neighbors and Decision Trees

## Lab objectives

* Classification with decision trees and random forests.
* Cross-validation and evaluation.

In [1]:
from lab_tools import CIFAR10, get_hog_image

dataset = CIFAR10('../../extern_data/CIFAR10/')

Pre-loading training data
Pre-loading test data


# 1. Nearest Neighbor

The following example uses the Nearest Neighbor algorithm on the Histogram of Gradient decriptors in the dataset.

## Notes:

**Hypothesis**: Samples which are close together in feature space belong to the same class.

**Fit**: Indexing the position of all samples

**Prediction**: Compute euclidian distance to points in training set. Find the k nearest neighbours. Prediction = majority class among those. Can be wighted by distance.


Hyper-parameyers:
- Number of neighboors
- Distance metric
- Weghts
+ preprocessing

In [131]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=10)
clf.fit( dataset.train['hog'], dataset.train['labels'] )

KNeighborsClassifier(n_neighbors=10)

* What is the **descriptive performance** of this classifier ?
* Modify the code to estimate the **predictive performance**.
* Use cross-validation to find the best hyper-parameters for this method.

In [3]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score

print("OH")
X_train, y_train = dataset.train['hog'], dataset.train['labels']
X_test, y_test = dataset.test['hog'], dataset.test['labels']

# NORMALIZATION
X_train = preprocessing.normalize(X_train, axis=0)
X_test = preprocessing.normalize(X_test, axis=0)

# PCA

#pca = PCA(n_components=30)
#pca.fit(X_train)

#X_train = pca.transform(X_train)
#X_test = pca.transform(X_test)

print("AH")
for n_neighbors in [15]:
    print(n_neighbors)
    clf = KNeighborsClassifier(n_neighbors=n_neighbors, weights='distance', p = 1)
    scores = cross_val_score(clf, X_train, y_train, cv=3) 

    #print(scores)
    print("With %f neighboor" % (n_neighbors))
    print("%0.3f accuracy with a standard deviation of %0.3f" % (scores.mean(), scores.std()))


#y_true, y_pred = y_test, clf.predict(X_test)

#print(classification_report(y_true, y_pred))

#pred = clf.predict(X_test)

#score = accuracy_score(y_test, pred)
#print(f"Normal Nearest Neighbor: {score:.3f}")

OH
AH
15
With 15.000000 neighboor
0.783 accuracy with a standard deviation of 0.005


In [ ]:

# -- Your code here -- #
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

X_train, y_train = dataset.train['hog'], dataset.train['labels']
X_test, y_test = dataset.test['hog'], dataset.test['labels']

# NORMALIZATION
X_train = preprocessing.normalize(X_train, axis=0)
X_test = preprocessing.normalize(X_test, axis=0)

# PCA

pca = PCA(n_components=77)
pca.fit(X_train)

X_train2 = pca.transform(X_train)
X_test2 = pca.transform(X_test)

clf = KNeighborsClassifier(n_neighbors=10, weights='distance', p = 1)
clf.fit( X_train2, y_train )

# PREDICTION
pred = clf.predict(X_test2)

score = accuracy_score(y_test, pred)
print(f"Normal Nearest Neighbor: {score:.3f}")
#cm = confusion_matrix(y_test, pred)
#print(cm)

"""
for nbcomp in np.arange(76,82,1):
    print(nbcomp)
    pca = PCA(n_components=nbcomp)
    pca.fit(X_train)

    X_train2 = pca.transform(X_train)
    X_test2 = pca.transform(X_test)

    #X_test = np.ascontiguousarray(PCA().fit_transform(X_test))

    # CLASSIFIER
    clf = KNeighborsClassifier(n_neighbors=10, weights='distance', p = 1)
    clf.fit( X_train2, y_train )

    # PREDICTION
    pred = clf.predict(X_test2)

    score = accuracy_score(y_test, pred)
    print(f"Normal Nearest Neighbor: {score:.3f}")
    #cm = confusion_matrix(y_test, pred)
    #print(cm)
"""
# ['Airplane', 'Bird', 'Horse']


## 2. Decision Trees

[Decision Trees](http://scikit-learn.org/stable/modules/tree.html#tree) classify the data by splitting the feature space according to simple, single-feature rules. Scikit-learn uses the [CART](https://en.wikipedia.org/wiki/Predictive_analytics#Classification_and_regression_trees_.28CART.29) algorithm for [its implementation](http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html) of the classifier. 

* **Create a simple Decision Tree classifier** using scikit-learn and train it on the HoG training set.
* Use cross-validation to find the best hyper-paramters for this method.

In [19]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train, y_train)

pred = clf.predict(X_test)

score = accuracy_score(y_test, pred)
print(f"Normal Nearest Neighbor: {score:.3f}")
cm = confusion_matrix(y_test, pred)
print(cm)


Normal Nearest Neighbor: 0.573
[[625 224 151]
 [212 519 269]
 [154 270 576]]


## 3. Random Forests

[Random Forest](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) classifiers use multiple decision trees trained on "weaker" datasets (less data and/or less features), averaging the results so as to reduce over-fitting.

* Use scikit-learn to **create a Random Forest classifier** on the CIFAR data. 
* Use cross-validation to find the best hyper-paramters for this method.

In [25]:
from sklearn.ensemble import RandomForestClassifier

# --- Your code here --- #

clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, y_train)

pred = clf.predict(X_test)

score = accuracy_score(y_test, pred)
print(f"Normal Nearest Neighbor: {score:.3f}")
cm = confusion_matrix(y_test, pred)
print(cm)



Normal Nearest Neighbor: 0.635
[[762 152  86]
 [200 551 249]
 [172 235 593]]
